package com.pojo;

// Generated 1 Jun, 2019 9:27:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer cid;
	private String cname;
	private String cimage;
	private Set properties = new HashSet(0);

	public Category() {
	}

	public Category(String cname, String cimage, Set properties) {
		this.cname = cname;
		this.cimage = cimage;
		this.properties = properties;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getCimage() {
		return this.cimage;
	}

	public void setCimage(String cimage) {
		this.cimage = cimage;
	}

	public Set getProperties() {
		return this.properties;
	}

	public void setProperties(Set properties) {
		this.properties = properties;
	}

}
