package com.pojo;

// Generated 1 Jun, 2019 9:27:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer cityid;
	private String cityname;
	private Set properties = new HashSet(0);

	public City() {
	}

	public City(String cityname, Set properties) {
		this.cityname = cityname;
		this.properties = properties;
	}

	public Integer getCityid() {
		return this.cityid;
	}

	public void setCityid(Integer cityid) {
		this.cityid = cityid;
	}

	public String getCityname() {
		return this.cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	public Set getProperties() {
		return this.properties;
	}

	public void setProperties(Set properties) {
		this.properties = properties;
	}

}
