package com.pojo;

// Generated 1 Jun, 2019 9:27:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Contactus generated by hbm2java
 */
public class Contactus implements java.io.Serializable {

	private Integer cid;
	private String name;
	private String email;
	private String msg;
	private Date date;

	public Contactus() {
	}

	public Contactus(String name, String email, String msg, Date date) {
		this.name = name;
		this.email = email;
		this.msg = msg;
		this.date = date;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
