package com.pojo;

// Generated 1 Jun, 2019 9:27:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Enquiry generated by hbm2java
 */
public class Enquiry implements java.io.Serializable {

	private Integer eid;
	private Property property;
	private Register registerByRegid;
	private Register registerByRid;
	private Date edate;
	private String message;

	public Enquiry() {
	}

	public Enquiry(Property property, Register registerByRegid, Register registerByRid, Date edate, String message) {
		this.property = property;
		this.registerByRegid = registerByRegid;
		this.registerByRid = registerByRid;
		this.edate = edate;
		this.message = message;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	public Register getRegisterByRegid() {
		return this.registerByRegid;
	}

	public void setRegisterByRegid(Register registerByRegid) {
		this.registerByRegid = registerByRegid;
	}

	public Register getRegisterByRid() {
		return this.registerByRid;
	}

	public void setRegisterByRid(Register registerByRid) {
		this.registerByRid = registerByRid;
	}

	public Date getEdate() {
		return this.edate;
	}

	public void setEdate(Date edate) {
		this.edate = edate;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
