package com.pojo;

// Generated 1 Jun, 2019 9:27:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Register generated by hbm2java
 */
public class Register implements java.io.Serializable {

	private Integer regid;
	private Role role;
	private String fname;
	private String lname;
	private String email;
	private String password;
	private String address;
	private String contact;
	private String status;
	private Date date;
	private String rimage;
	private String description;
	private Set properties = new HashSet(0);
	private Set enquiriesForRegid = new HashSet(0);
	private Set enquiriesForRid = new HashSet(0);

	public Register() {
	}

	public Register(Role role, String fname, String lname, String email, String password, String address,
			String contact, String status, Date date, String rimage, String description, Set properties,
			Set enquiriesForRegid, Set enquiriesForRid) {
		this.role = role;
		this.fname = fname;
		this.lname = lname;
		this.email = email;
		this.password = password;
		this.address = address;
		this.contact = contact;
		this.status = status;
		this.date = date;
		this.rimage = rimage;
		this.description = description;
		this.properties = properties;
		this.enquiriesForRegid = enquiriesForRegid;
		this.enquiriesForRid = enquiriesForRid;
	}

	public Integer getRegid() {
		return this.regid;
	}

	public void setRegid(Integer regid) {
		this.regid = regid;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getRimage() {
		return this.rimage;
	}

	public void setRimage(String rimage) {
		this.rimage = rimage;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getProperties() {
		return this.properties;
	}

	public void setProperties(Set properties) {
		this.properties = properties;
	}

	public Set getEnquiriesForRegid() {
		return this.enquiriesForRegid;
	}

	public void setEnquiriesForRegid(Set enquiriesForRegid) {
		this.enquiriesForRegid = enquiriesForRegid;
	}

	public Set getEnquiriesForRid() {
		return this.enquiriesForRid;
	}

	public void setEnquiriesForRid(Set enquiriesForRid) {
		this.enquiriesForRid = enquiriesForRid;
	}

}
